// ---------------------------------------------------------------------
// THIS FILE IS AUTO-GENERATED BY BEHAVIAC DESIGNER, SO PLEASE DON'T MODIFY IT BY YOURSELF!
// ---------------------------------------------------------------------

#include "../behaviac_types.h"

// -------------------
// Customized enums
// -------------------

BEHAVIAC_BEGIN_ENUM_EX(ETest, ETest)
{
	BEHAVIAC_ENUMCLASS_DISPLAY_INFO_EX(L"ETest", L"");

	BEHAVIAC_ENUM_ITEM_EX(EA, "EA");
	BEHAVIAC_ENUM_ITEM_EX(EB, "EB");
	BEHAVIAC_ENUM_ITEM_EX(EC, "EC");
}
BEHAVIAC_END_ENUM_EX()

