// ---------------------------------------------------------------------
// THIS FILE IS AUTO-GENERATED BY BEHAVIAC DESIGNER, SO PLEASE DON'T MODIFY IT BY YOURSELF!
// ---------------------------------------------------------------------

#ifndef _BEHAVIAC_AGENT_PROPERTIES_H_
#define _BEHAVIAC_AGENT_PROPERTIES_H_

#include "behaviac_agent_headers.h"
#include "behaviac_agent_member_visitor.h"
#include "behaviac_customized_types.h"

namespace behaviac
{
	// ---------------------------------------------------------------------
	// Delegate methods
	// ---------------------------------------------------------------------

	inline void FunctionPointer_behaviac_Agent_LogMessage(char* param0) { behaviac::Agent::LogMessage(param0); }
	inline void FunctionPointer_PlaneEnemy_applyForce(Agent* self, Vec2& param) { ((PlaneEnemy*)self)->_Execute_Method_<METHOD_TYPE_PlaneEnemy_applyForce, void, Vec2 >(param); }
	inline void FunctionPointer_PlaneEnemy_avoid(Agent* self) { ((PlaneEnemy*)self)->_Execute_Method_<METHOD_TYPE_PlaneEnemy_avoid, void >(); }
	inline void FunctionPointer_PlaneEnemy_boundaries(Agent* self) { ((PlaneEnemy*)self)->_Execute_Method_<METHOD_TYPE_PlaneEnemy_boundaries, void >(); }
	inline void FunctionPointer_PlaneEnemy_eat(Agent* self) { ((PlaneEnemy*)self)->_Execute_Method_<METHOD_TYPE_PlaneEnemy_eat, void >(); }
	inline void FunctionPointer_PlaneEnemy_LogMessage(char* param0) { PlaneEnemy::LogMessage(param0); }
	inline void FunctionPointer_PlaneEnemy_mate(Agent* self) { ((PlaneEnemy*)self)->_Execute_Method_<METHOD_TYPE_PlaneEnemy_mate, void >(); }
	inline void FunctionPointer_PlaneEnemy_randomRotate(Agent* self) { ((PlaneEnemy*)self)->_Execute_Method_<METHOD_TYPE_PlaneEnemy_randomRotate, void >(); }
	inline void FunctionPointer_PlaneEnemy_updatePosition(Agent* self) { ((PlaneEnemy*)self)->_Execute_Method_<METHOD_TYPE_PlaneEnemy_updatePosition, void >(); }
	inline void FunctionPointer_PlaneEnemy_wander(Agent* self) { ((PlaneEnemy*)self)->_Execute_Method_<METHOD_TYPE_PlaneEnemy_wander, void >(); }
}
#endif // _BEHAVIAC_AGENT_PROPERTIES_H_
