// ---------------------------------------------------------------------
// THIS FILE IS AUTO-GENERATED BY BEHAVIAC DESIGNER, SO PLEASE DON'T MODIFY IT BY YOURSELF!
// ---------------------------------------------------------------------

#ifndef _BEHAVIAC_CUSTOMIZED_TYPES_H_
#define _BEHAVIAC_CUSTOMIZED_TYPES_H_

#include "behaviac/agent/agent.h"

// -------------------
// Customized enums
// -------------------

enum ETest
{
	EA,
	EB = 1,
};

DECLARE_BEHAVIAC_ENUM_EX(ETest, ETest);
BEHAVIAC_DECLARE_TYPE_VECTOR_HANDLER(ETest);


// -------------------
// Customized structs
// -------------------

BEHAVIAC_EXTEND_EXISTING_TYPE_EX(Vec2, false);
BEHAVIAC_DECLARE_TYPE_VECTOR_HANDLER(Vec2);

template< typename SWAPPER >
inline void SwapByteImplement(Vec2& v)
{
}

namespace behaviac
{
	namespace PrivateDetails
	{
		template<>
		inline bool Equal(const Vec2& lhs, const Vec2& rhs)
		{
			return &lhs == &rhs;
		}
	}
}

#endif // _BEHAVIAC_CUSTOMIZED_TYPES_H_
