// ---------------------------------------------------------------------
// THIS FILE IS AUTO-GENERATED BY BEHAVIAC DESIGNER, SO PLEASE DON'T MODIFY IT BY YOURSELF!
// ---------------------------------------------------------------------

#include "behaviac/behaviac.h"

#include "behaviac_generated_behaviors.h"

namespace behaviac
{
	class CppGenerationManager : GenerationManager
	{
	public:
		CppGenerationManager()
		{
			SetInstance(this);
		}

		virtual void RegisterBehaviorsImplement()
		{
			Workspace::GetInstance()->RegisterBehaviorTreeCreator("enemy", bt_enemy::Create);
			Workspace::GetInstance()->RegisterBehaviorTreeCreator("hero", bt_hero::Create);
			Workspace::GetInstance()->RegisterBehaviorTreeCreator("npc", bt_npc::Create);
		}
	};

	CppGenerationManager _cppGenerationManager_;
}
